name: Build main solution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
          # Change to your required .NET version if needed

      - name: Restore dependencies
        run: dotnet restore
        working-directory: Source

      - name: Build solution
        run: dotnet build --no-restore --configuration Debug
        working-directory: Source

      - name: exclude results directory
        run: |
          rm -rf Builld/Results

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            Build/
          if-no-files-found: error
